version: 2.1
orbs:
  node: circleci/node@3.0.0

defaults: &defaults
  working_directory: /tmp/repo
  docker:
    - image: circleci/node:12

workflows:
  on-commit:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install

  on-tag:
    jobs:
      - install:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - install
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  # Install all dependencies
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: /tmp
          paths:
            - repo

  # Run unit tests
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/
      - run:
          name: Run tests
          command: npm test

  # Build
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/
      - run:
          name: Build Typescript
          command: npm run build
      - persist_to_workspace:
          root: /tmp
          paths:
            - repo

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > /tmp/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
